addons:
  apt:
    packages:
    - python-pygments
install:
- rm -rf public || exit 0
script:
- binaries/hugo
deploy:
  provider: firebase
  local_dir: public
  skip_cleanup: true
  token:
    secure: kFcFUN4qBMuhTFxdVDLDf4MLtaoLObI7h0JMeNdF7s3+AlJzs3ekWZ/FpqBMPqjXoTU73/PHPxLIEbENP+Y2/4BnPfJyX9VqOdN/iPkOygDacrLFXdffqJUUhNsO9YReQ45NDnCCCh21/FsJ2AIwEseaDbqmgIjmkPyCQaxtpXdbTS482oMcAEiPv2CakOEoO382l8BYqPBgMSGXBkG7nmNGilKRvkOgiXiUEvo3sAScXUq1vPQzEDjbDhEHE9DFgi2+Psv4spkck+yb/laxx8AThTXyfWio+q4sw8KiPHDO0BVbYniXOf/h6HeTdjEiloRf6isVVo/d90oG5J9uoszDSN97xjisR1C61gMdv4szS+B3xtM9Uwjm/xqMLrX/xd/vC0GBqzOXli1aqenc9+gMixsTM8I7Hgrrh6+MIilMEIiMi9hlhX9BXEg6xBHE8cRGYCP39y0OE1cWus0JSv8AfpDK6SIU3Hiww+3gyssT08juReLcfb7gB1LU745uIOQllm6mSh20htHKFATnoP8aVALuqAwMlZT+2hTVC/4KOBMDryVdbk8Uj5EDVJTHMaVupDzrNndBL1kNGGMcScpih3xCKOccHP9G7iM9JkDYvph2HkqTg1NbyLFg6SQcFMXCIwl9eDnDoc0xbe6nJQPbjNzmAlxiIKEDbD5fhQM=
  project: onisa-org-za
