addons:
  apt:
    packages:
    - python-pygments
install:
- rm -rf public || exit 0
script:
- binaries/hugo
deploy:
  provider: firebase
  local_dir: public
  skip_cleanup: true
  token:
    secure: JMVY9WoSE5NfjoOSUcT3aPdEXiHkbgz9tBwqkrC29CkOX0VzLA2hrGe1nxyTUu1wDbZDiwf7lp5lCUozX2xIu+uCETHykHwnivnIAcI4j0k/TnN4DAq6FRlVahSr34DjXwI3tEnI5Er4fV7GcaCKsdeF3nNxY8+2M9PFADmKwNlTYAQFRllkkHO59a0Rgg2aY5/f6r+5BhIKTMjEBrtVpBp7QWfnj58Kj5ibjmtsGareOiCh2ViKFqDNT6YL1wbAWBX0fQgbIYaAy6nPlgbrVrZ43d5gMwJWRJlCQ5H0KXgEc3LfngpugmDYBPv53dZYqOLsEeq84qsixuES8IJbSSJaHa9EBKSLgcBZrQrj4woly9R7hvh13J6M0MYnmR+WQESL59MG3rMN7dnyGMYgy7pJcC4zusTkz2CRuBx2l+xBGv8WcLVm5pil7p5kKhhtpRIUSaOMZlnTGEBHZAmhOfXx4lxyMY7DKJ6yJsYj/hph9qGojXIj2N8xBR0GWAQFmJSl2gy0QO1ie0jnX6p9TVQaRO5wZNZMUfc0Y5HGflcrndkoZ4WybIjCkXEfUnwueEzF5aSaUm4t3QXUuGR4aAJawz6mDmDUtxPaHOwGKPJQfKohH8QYqilkfzUSJhzNN6+kcwAGYKMbthfcvqN3NJohMKhw22iriZjGbSciWXA=
  project: www-onisa-org-za
