addons:
  apt:
    packages:
    - python-pygments
install:
- rm -rf public || exit 0
script:
- binaries/hugo
deploy:
  provider: firebase
  local_dir: public
  skip_cleanup: true
  token: 
    secure: aXOnYIDmG1+fdEyW+OHqT/wYq0VkBcTXcgkhEzbBBXr0D0x9rO+zom/TXNYvxwVakeEHJb5mxhQn2mYuFTXskUsvxJjqguQLo0PRBvssQ8Gm/k2yY3TWMIEdQrHDleSHW/H96VC0qH9cjPDR0tE1VX5X2EpwHbEk4rbz+L4cW+594/XoHiEGXik7hCottsil3RkIk4ObX80cRrOZa6w5aEZyOSoS4RdM+Wm/cmZFbQWN3yV7DUeRL42U1UY/sOHm5WXOL7FLjKWBJcCEQW2BlDTRVXcrASdC3wX7Eajvtv5O3vuFdwkGceRaJPjJMeXoYbfOs8yCqrcHrdtDH5QMJ0mDnYIQkVrbyqd9Kj9es17GupF+pnm1Pf/wVpXqle94iO+R/1jv8wBXOKJJvPD8AuEOVUEPYeNAoJ3mL5m5bJ4442stjZHhNcdXUAB+yCkm3fiVu2g6prntPcBxgyrlNz2L/rmnPW1tP6Bkf5MnTaURUKki6j79lGiWGy0zIRR2sXXM4Kj1kObVbQwJ+/4oH/azqa1gNzeD+xlsB2zsRywpSsFgo+lLe3LrErsFKqrj8TTArfC4Mt9wRUUF61LtOa752bi3mGAzWgQLG4SZgopQj4VEFi3wZ9z02+JqcXYgkANR/I32ucSMNqxWisIpzDZR5w/QWRBjudoxMjfj+cE=
  project: onisa-org-za
